export const PRODUCTS_LOADING = "PRODUCTS_LOADING";
export const LOAD_PRODUCTS = "LOAD_PRODUCTS";
export const PRODUCTS_LOADING_ERROR = "PRODUCTS_LOADING_ERROR";

export const ADD_PRODUCT = "ADD_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
