import { Button, Typography } from "@material-tailwind/react";
import Head from "next/head";
import Link from "next/link";
import React from "react";

const Dashboard = ({ title = "Aliro - Dashboard", children, className }) => {
    return (
        <>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <title>{title}</title>
            </Head>
            <div className="grid grid-cols-[20rem_1fr] p-6 gap-6">
                <div className="h-[calc(100vh-48px)] p-6 border rounded-lg">
                    <div className="flex gap-2 flex-col h-full">
                        <Typography variant="h3" className="text-center">
                            Admin Dashboard
                        </Typography>
                        <Link href="/dashboard">
                            <Button fullWidth>Product List</Button>
                        </Link>
                        <Link href="/dashboard/add-product">
                            <Button fullWidth> Add Product</Button>
                        </Link>
                        <Link href="/">
                            <Button variant="outlined" fullWidth>
                                Back to Home
                            </Button>
                        </Link>
                    </div>
                </div>
                <div className={`w-full border rounded-lg ${className}`}>{children}</div>
            </div>
        </>
    );
};

export default Dashboard;
