import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { useState } from "react";
import { Button, IconButton, MobileNav, Navbar, Switch, Typography } from "@material-tailwind/react";
import LightLogo from "../public/logo/light.jpeg";
import { useTheme } from "next-themes";
import { CgClose, CgMenuRight } from "react-icons/cg";

const Main = ({ title = "Aliro Content Management" }) => {
    const { theme, setTheme } = useTheme();
    const [openNav, setOpenNav] = useState(false);

    const navList = (
        <div className="mb-4 mt-2 flex flex-col gap-2 lg:mb-0 lg:mt-0 lg:flex-row lg:items-center lg:gap-6">
            <Link href="/" className="flex items-center">
                Home
            </Link>
            <Link href="/top-rated" className="flex items-center">
                Top Rated
            </Link>
            <Link href="/about" className="flex items-center">
                About
            </Link>
            <Link href="/dashboard" className="flex items-center">
                Dashboard
            </Link>
        </div>
    );

    return (
        <>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <title>{title}</title>
            </Head>
            <nav className="border-b text-content">
                <div className="container py-4 flex items-center justify-between">
                    <Image src={LightLogo} alt="" width={100} />
                    <div className="hidden lg:block">{navList}</div>
                    <div className="inline-flex items-center gap-4">
                        <Switch checked={theme === "dark" ? true : false} onChange={() => (theme === "light" ? setTheme("dark") : setTheme("light"))} />
                        <Button size="sm" className="hidden lg:inline-block">
                            Sign In
                        </Button>
                        <IconButton
                            ripple={false}
                            variant="text"
                            className="ml-auto h-6 w-6 text-inherit hover:bg-transparent focus:bg-transparent active:bg-transparent lg:hidden"
                            onClick={() => setOpenNav(!openNav)}
                        >
                            {openNav ? <CgMenuRight size={24} /> : <CgClose size={24} />}
                        </IconButton>
                    </div>
                </div>
                <MobileNav open={openNav}>
                    <div className="container mx-auto lg:hidden">
                        {navList}
                        <Button size="sm" fullWidth className="mb-6">
                            <span>Buy Now</span>
                        </Button>
                    </div>
                </MobileNav>
            </nav>
        </>
    );
};

export default Main;
